### ISSUE TITLE
Sketch v69 Color vars issue

### ISSUE THREAD

**Issue by MihaelN** [design-meets-development/design-tokens-plugin#12]
Hi,
My team and I have faced a problem with the plugin when it comes to using new Sketch v69 Color Variables. Tokens are not generated in this case and `.json` file generated is empty.

Any plans for the update? Thanks a lot for the plugin, it has been great to use so far.

**Comment by vjandrei** [comment]
Hi, @MihaelN I need to check the issue soon. 
I have been busy and these 69 version updates are not yet ready.
I will let you know when I have new fix update out.

**Comment by vjandrei** [comment]
@MihaelN Hi, I just test it 69.1 Sketch beta and there was no issue about tokens export.
Can you explain the problem in more detail thanks. If you have some example of the Sketch file you try to export please send it to me and I can debug it.

**Comment by vjandrei** [comment]
There was no issue about Sketch 69.1 tested.
