### ISSUE TITLE
Why no font-weight output?

### ISSUE THREAD

**Issue by jkinley** [design-meets-development/design-tokens-plugin#14]
"body": {
            "font-family": {
                "value": "Helvetica"
            },
            "font-size": {
                "value": 12
            },
            "weight": {}, // no output here?
            "letter-spacing": {
                "value": 0
            },
            "line-height": {
                "value": 16
            },
            "type": "typography"

**Comment by vjandrei** [comment]
I need to check this issue soon.

**Comment by vjandrei** [comment]
@jkinley So there was a bug in the code to for printing the weight number.
But in the Sketch API document there is only number value for the weights. I will build soon new fix release.

[API Document](https://developer.sketch.com/reference/api/#style)
`fontWeightnumber | The weight of the font of a Text Layer. Goes from 0 to 12, 0 being the thinest and 12 being the boldest. Not every weight are available for every fonts. When setting a font weight that does not exist for the current font family, the closest weight that exists will be set instead.`
